#
# Makefile for the cypress-touchkey drivers.
#
obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH)                += cypress-touchkey.o
obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH)                += issp_driver_routines.o
obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH)                += issp_main.o
obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH)                += issp_routines.o
